#!/bin/bash
#SBATCH --constraint=knl
#SBATCH --nodes=1
#SBATCH --time=01:30:00

# module load python
echo "BLOCKING BENCHMARKING"

srun -N 1 --ntasks-per-node=30 python diag-mpi-sw.py --length 10 --seed 1
srun -N 1 --ntasks-per-node=30 python diag-mpi-sw.py --length 100 --seed 1
srun -N 1 --ntasks-per-node=30 python diag-mpi-sw.py --length 1000 --seed 1
srun -N 1 --ntasks-per-node=30 python diag-mpi-sw.py --length 10000 --seed 1